### ISSUE TITLE
When a player dies, all the clients panic

### ISSUE THREAD

**Issue by DomonkosSuranyi** [DomonkosSuranyi/westiny#87]
one:
`thread 'Compute Task Pool (3)' panicked at 'called 'Result::unwrap()' on an 'Err' value: NoEntities("bevy_ecs::query::state::QueryState<(&mut westiny_common::components::health::Health, &mut westiny_client::components::weapon_info::WeaponInfo), bevy_ecs::query::filter::With<westiny_common::components::player::Player>>")', client/src/systems/player_update.rs:13:54`

`thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value', /home/surdom/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.9.1/src/task_pool.rs:273:45`

other one:
`thread 'main' panicked at 'error[B0003]: Could not insert a bundle (of type 'bevy_sprite::texture_atlas::TextureAtlasSprite') for entity 6177v7 because it doesn't exist in this World.', /home/surdom/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/system/commands/mod.rs:840:13`

**Comment by susu** [comment]
I could reproduce it twice, second time only the client of the dying player panicked.

```
thread 'main' panicked at client/src/systems/player_update.rs:13:54:
called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<(&mut westiny_common::components::health::Health, &mut westiny_client::components::weapon_info::WeaponInfo), bevy_ecs::query::filter::With<westiny_common::components::player::Player>>")

```
